### ISSUE TITLE
rebar3 support doesn't always work

### ISSUE THREAD

**Issue by tuncer** [tuncer/re2#13]
If you attempt to compile with rebar3, it only works intermittently. More specifically, the pre_hook gets ignored. I've gotten it to compile twice (just as it worked back when I added rebar3 support), but I haven't figured out the exact circumstances under which the hook is run successfully, in order to get to the root issue.

To reliably cause a failed compile as reported by @matehat, you can run this:

```
$ git clean -fxd ; rm -r ~/.cache/rebar3 ; rebar3 compile
```

This isn't the only way to provoke the error, but it's a sure way to reproduce and it's not supposed to fail like this.

Running this will completely skip the `c_src/build_deps.sh` compile pre_hook and therefore go looking for re2.h and libre2.so on the system. If you have re2 as a system package, it will find and use it. But, this is not how it's meant to work.

Because this worked a couple times, it's safe to assume there's an underlying issue in rebar3.

**Comment by ferd** [comment]
What would I need to be able to reproduce this? I don't have re2.h or libre2.so on the system as far as I know.

**Comment by matehat** [comment]
@ferd then just pulling this very library and attempting to build it using rebar3 will fail

**Comment by ferd** [comment]
I get the following output:

```
 → DEBUG=1 rebar3 compile
===> Evaluating config script "rebar.config.script"
===> Load global config file /home/ferd/.config/rebar3/rebar.config
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {default,install_deps},
                                                  {default,lock},
                                                  {default,compile}]
===> Evaluating config script "/tmp/re2/rebar.config.script"
===> Not adding provider pc compile from module pc_prv_compile because it already exists from module pc_prv_compile
===> Not adding provider pc clean from module pc_prv_clean because it already exists from module pc_prv_clean
===> Evaluating config script "/tmp/re2/rebar.config.script"
===> Not adding provider pc compile from module pc_prv_compile because it already exists from module pc_prv_compile
===> Not adding provider pc clean from module pc_prv_clean because it already exists from module pc_prv_clean
===> Verifying dependencies...
===> run_hooks("/tmp/re2", pre_hooks, compile) -> no hooks defined

===> sh info:
        cwd: "/tmp/re2"
        cmd: cp -Rp /tmp/re2/ebin/re2.app "/tmp/re2/_build/default/lib/re2/ebin"

===>    opts: [{use_stdout,false},abort_on_error]

===> Port Cmd: cp -Rp /tmp/re2/ebin/re2.app "/tmp/re2/_build/default/lib/re2/ebin"
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> Compiling re2
===> sh info:
        cwd: "/tmp/re2"
        cmd: c++ -c -m64  -g -Wall -fPIC -MMD  -I"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include" -I"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2 /tmp/re2/c_src/re2_nif.cpp -o /tmp/re2/c_src/re2_nif.o

===>    opts: [{env,[{"BINDIR",
                              "/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/bin"},
                             {"CC","cc"},
                             {"CFLAGS","-m64 "},
                             {"CXX","c++"},
                             {"CXXFLAGS","-m64 "},
                             {"DEBUG","1"},
                             {"DRV_CC_TEMPLATE",
                              "cc -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2 $PORT_IN_FILES -o $PORT_OUT_FILE"},
                             {"DRV_CFLAGS",
                              "-g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2"},
                             {"DRV_CXX_TEMPLATE",
                              "c++ -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2 $PORT_IN_FILES -o $PORT_OUT_FILE"},
                             {"DRV_LDFLAGS",
                              "-shared  -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei c_src/re2/obj/libre2.a"},
                             {"DRV_LINK_TEMPLATE",
                              "cc $PORT_IN_FILES  -lstdc++ -shared  -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei c_src/re2/obj/libre2.a -o $PORT_OUT_FILE"},
                             {"EDITOR","/home/ferd/local/bin/vim"},
                             {"EMU","beam"},
                             {"ERLANG_ARCH","64"},
                             {"ERLANG_TARGET",
                              "18.1.5-x86_64-unknown-linux-gnu-64"},
                             {"ERL_CFLAGS",
                              " -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"  "},
                             {"ERL_EI_LIBDIR",
                              "\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\""},
                             {"ERL_LDFLAGS",
                              " -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei"},
                             {"EXE_CC_TEMPLATE",
                              "cc -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   $PORT_IN_FILES -o $PORT_OUT_FILE"},
                             {"EXE_CFLAGS",
                              "-g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"  "},
                             {"EXE_CXX_TEMPLATE",
                              "c++ -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   $PORT_IN_FILES -o $PORT_OUT_FILE"},
                             {"EXE_LDFLAGS",
                              " -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei"},
                             {"EXE_LINK_TEMPLATE",
                              "cc $PORT_IN_FILES  -lstdc++  -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei -o $PORT_OUT_FILE"},
                             {"GHAUTH",
                              "af0ebc9e9118ada591f185f7b55c112d9ec52085"},
                             {"GREP_COLOR","1;32"},
                             {"HOME","/home/ferd"},
                             {"LANG","en_CA.UTF-8"},
                             {"LC_ALL","en_CA.UTF-8"},
                             {"LC_CTYPE","en_CA.UTF-8"},
                             {"LDFLAGS"," -lstdc++"},
                             {"LESS","-R"},
                             {"LOGNAME","ferd"},
                             {"LSCOLORS","Gxfxcxdxbxegedabagacad"},
                             {"MAIL","/var/mail/ferd"},
                             {"OLDPWD","/tmp"},
                             {"PAGER","less"},
                             {"PATH",
                              "/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/bin:/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/bin:/home/ferd/local/bin:/home/ferd/.erln8.d/bin:/hom$e/ferd/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ferd/.oh-my-vim/bin:/home/ferd/.oh-my-vim/bin"},
                             {"PROGNAME","erl"},
                             {"PWD","/tmp/re2"},
                             {"ROOTDIR",
                              "/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang"},
                             {"SHELL","/bin/zsh"},
                             {"SHLVL","3"},
                             {"SSH_CLIENT","24.203.235.12 49796 22"},
                             {"SSH_CONNECTION",
                              "96.21.189.171 58242 168.235.69.158 22"},
                             {"SSH_TTY","/dev/pts/3"},
                             {"TEMP","/tmp/user/1001"},
                             {"TEMPDIR","/tmp/user/1001"},
                             {"TERM","screen"},
                             {"TMP","/tmp/user/1001"},
                             {"TMPDIR","/tmp/user/1001"},
                             {"TMUX",
                              "/tmp/user/1001/tmux-1001/default,1031,0"},
                             {"TMUX_PANE","%196"},
                             {"USER","ferd"},
                             {"_","/home/ferd/local/bin/rebar3"}]},
                       return_on_error,
                       {use_stdout,false},
                       {cd,"/tmp/re2"}]

===> Port Cmd: c++ -c -m64  -g -Wall -fPIC -MMD  -I"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include" -I"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2 /tmp/re2/c_src/re2_nif.cpp -o /tmp/re2/c_src/re2_nif.o

Port Opts: [{env,[{"BINDIR",
                   "/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/bin"},
                  {"CC","cc"},
                  {"CFLAGS","-m64 "},
                  {"CXX","c++"},
                  {"CXXFLAGS","-m64 "},
                  {"DEBUG","1"},
                  {"DRV_CC_TEMPLATE",
                   "cc -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts/7.1/include\"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2 $PORT_IN_FILES -o $PORT_OUT_FILE"},
                  {"DRV_CFLAGS",
                   "-g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include/"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2"},
                  {"DRV_CXX_TEMPLATE",
                   "c++ -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   -O3 -Wall -Wextra -std=c++11 -Ic_src/re2 $PORT_IN_FILES -o $PORT_OUT_FILE"},
                  {"DRV_LDFLAGS",
                   "-shared  -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei c_src/re2/obj/libre2.a"},
                  {"DRV_LINK_TEMPLATE",
                   "cc $PORT_IN_FILES  -lstdc++ -shared  -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei c_src/re2/obj/libre2.a -o $PORT_OUT_FILE"},
                  {"EDITOR","/home/ferd/local/bin/vim"},
                  {"EMU","beam"},
                  {"ERLANG_ARCH","64"},
                  {"ERLANG_TARGET","18.1.5-x86_64-unknown-linux-gnu-64"},
                  {"ERL_CFLAGS",
                   " -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"  "},
                  {"ERL_EI_LIBDIR",
                   "\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\""},
                  {"ERL_LDFLAGS",
                   " -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei"},
                  {"EXE_CC_TEMPLATE",
                   "cc -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   $PORT_IN_FILES -o $PORT_OUT_FILE"},
                  {"EXE_CFLAGS",
                   "-g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"  "},
                  {"EXE_CXX_TEMPLATE",
                   "c++ -c -m64  -g -Wall -fPIC -MMD  -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/include\" -I\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/include\"   $PORT_IN_FILES -o $PORT_OUT_FILE"},
                  {"EXE_LDFLAGS",
                   " -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei"},
                  {"EXE_LINK_TEMPLATE",
                   "cc $PORT_IN_FILES  -lstdc++  -L\"/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/lib/erl_interface-3.8/lib\" -lerl_interface -lei -o $PORT_OUT_FILE"},
                  {"GHAUTH","af0ebc9e9118ada591f185f7b55c112d9ec52085"},
                  {"GREP_COLOR","1;32"},
                  {"HOME","/home/ferd"},
                  {"LANG","en_CA.UTF-8"},
                  {"LC_ALL","en_CA.UTF-8"},
                  {"LC_CTYPE","en_CA.UTF-8"},
                  {"LDFLAGS"," -lstdc++"},
                  {"LESS","-R"},
                  {"LOGNAME","ferd"},
                  {"LSCOLORS","Gxfxcxdxbxegedabagacad"},
                  {"MAIL","/var/mail/ferd"},
                  {"OLDPWD","/tmp"},
                  {"PAGER","less"},
                  {"PATH",
                   "/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/erts-7.1/bin:/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang/bin:/home/ferd/local/bin:/home/ferd/.erln8.d/bin:/home/ferd/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ferd/.oh-my-vim/bin:/home/ferd/.oh-my-vim/bin"},
                  {"PROGNAME","erl"},
                  {"PWD","/tmp/re2"},
                  {"ROOTDIR",
                   "/home/ferd/.erln8.d/otps/OTP-18.1.5/dist/lib/erlang"},
                  {"SHELL","/bin/zsh"},
                  {"SHLVL","3"},
                  {"SSH_CLIENT","24.203.235.12 49796 22"},
                  {"SSH_CONNECTION","96.21.189.171 58242 168.235.69.158 22"},
                  {"SSH_TTY","/dev/pts/3"},
                  {"TEMP","/tmp/user/1001"},
                  {"TEMPDIR","/tmp/user/1001"},
                  {"TERM","screen"},
                  {"TMP","/tmp/user/1001"},
                  {"TMPDIR","/tmp/user/1001"},
                  {"TMUX","/tmp/user/1001/tmux-1001/default,1031,0"},
                  {"TMUX_PANE","%196"},
                  {"USER","ferd"},
                  {"_","/home/ferd/local/bin/rebar3"}]},
            {cd,"/tmp/re2"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> Compiling /tmp/re2/c_src/re2_nif.cpp
===> /tmp/re2/c_src/re2_nif.cpp:8:21: fatal error: re2/re2.h: No such file or directory
 #include <re2/re2.h>
                     ^
compilation terminated.
```

The code seems to execute fine, it just fails. That's all hooks and plugins outside of rebar3 core?

**Comment by tuncer** [comment]
@ferd, run it with `DEBUG_CONFIG=1` in order to enable a printout of the `rebar.config.script` result. There you will see the full config, which includes the pre_hook that only has been triggered intermittently so far. Don't worry about the printout happening thrice. That's this rebar3 bug: https://github.com/rebar/rebar3/issues/1087.

I suppose this (from your log above)

```
===> run_hooks("/tmp/re2", pre_hooks, compile) -> no hooks defined
```

shouldn't say `no hooks defined`, for the build to work correctly.

**Comment by ferd** [comment]
Understood.

**Comment by ferd** [comment]
I haven't gotten things to work in 3.0.0, 3.1.0, 3.2.0 and master branches. Has this ever worked?

**Comment by tsloughter** [comment]
Provider hooks run before the other hooks. Looks like your provider hook (pc compile) depends on the `pre_hook` on compile to have run before it.

That is probably the issue.

**Comment by tsloughter** [comment]
The solution I'd suggest is adding hook calls to the port compiler plugin so that you can hook into `{pc, compile}` as a pre hook.

**Comment by tuncer** [comment]
@fred wrote:
> Has this ever worked?

Yes, reliably back in March, but intermittently this week. @tsloughter's explanation would explain the behavior. To be clear, the config is based on the docs found on the website, so should those be revised accordingly?

Will try it out tomorrow if nobody submits a diff first.

**Comment by tuncer** [comment]
@tsloughter, is it correct that it says

```
run_hooks("/tmp/re2", pre_hooks, compile) -> no hooks defined
```
though?

**Comment by tuncer** [comment]
@tsloughter I found no way to hook into pc's pre_compile or alternatively run a shell script in provider_hooks. What exactly is your suggested solution?

Also, is `run_hooks("/tmp/re2", pre_hooks, compile) -> no hooks defined` correct behavior, given the existence of pre_hooks in the config?

**Comment by tsloughter** [comment]
Right, I was saying that hook support would have to be added to the port compiler plugin first.

Yea, there are 2 places pre_hooks for compile are run. Once for the project and once per-app. That one you see that has no hooks defined is probably that project run.

The only time project hooks are different (or can exist) from per-app hooks is when you have an umbrella project where you have multiple apps under `apps/`.

**Comment by tuncer** [comment]
It's 1 project, which is 1 app, so I'm not sure if the warning should be logged.

**Comment by ferd** [comment]
So I didn't implement the hooks, but my understanding of them is as follows:

A hook can be global to the full compile step (entire project), or to a specific application run (app is compiled, you run before and after). See http://www.rebar3.org/docs/configuration#section-hookable-points-in-providers

Edocs, for example, has its hooks run only before and after the entire run. Similarly for release or eunit, since they run only for the top-level project and not for dependencies.

The compile hook is, by default, running for every application, because dependencies must specify their own hook in their own context. The distinction is that in some cases (umbrella apps), hooks can be defined on many levels (omitting overrides):

- the root rebar.config
- each top-level app's (in apps/ or libs/) rebar.config
- each dependency's rebar.config

By default, when you don't have umbrella apps, the hook defined in the top-level rebar.config is attributed to be part of 'each top-level app', which means the behaviour and context keeps working for a dependency.

Now the suspicion here is that the first log line you see is for the root rebar config's hooks in a umbrella setting. Since re2 is not an umbrella setting, no hook is detected for it.

The hooks then go for provider hooks, in this case `pc` since it is first in the list, and there it fails, without having had the opportunity to call your own shell hook from within the app-level.

The solution Tristan is recommending is adding a hookable sequence to the `pc` plugin itself, such that you can run your shell hook on top of the `pc` plugin, rather than `compile` (which has the `pc` hook running before your shell hook).

**Comment by tsloughter** [comment]
I'm going to add a section to the plugins tutorial on rebar3.org about how to make your plugin hookable.

**Comment by tsloughter** [comment]
But basically you just need to add:

```
rebar_hooks:run_all_hooks(Cwd, pre, ?PROVIDER, Providers, State),
```

to `pc_prv_compile`.

**Comment by tuncer** [comment]
Suppose, port_compiler is fixed, how would the hook to run the shell script look in rebar.config?

**Comment by tuncer** [comment]
@ferd there is no umbrella project, it's just a single app project. Therefore, the current log message, even if technically correct, is confusing. I suggest to make it more specific or at least not make it look like a false warning.

**Comment by tsloughter** [comment]
`{pre_hooks, [{{pc, compile}, "c_src/build_deps.sh"}]},`

**Comment by tuncer** [comment]
But that wouldn't fit the type spec.

```
-type hook() :: {atom(), string()}
              | {string(), atom(), string()}.

{pre_hooks, [hook()]}.
{post_hooks, [hook()]}.
```

**Comment by tuncer** [comment]
BTW, why do plugins need to explicitly add a call to rebar_hooks? Is there some flexibility gained by that which would otherwise be harder to support?

**Comment by tuncer** [comment]
While thinking of workarounds, I wondered if one could write a source-only plugin (.erl) as part of the project, and if that would already be hook-ready.

**Comment by tsloughter** [comment]
Ah, you are right, the type spec needs to be updated and the call in `pc` should be `rebar_hooks:run_all_hooks(Cwd, pre, {?NAMESPACE, ?PROVIDER}, Providers, State),`

Originally we attempted to have hooks be part of providers themselves, making every provider hookable, this turned out to be very flawed. I can't think at the moment what those issues were.

**Comment by tuncer** [comment]
See https://github.com/blt/port_compiler/pull/24

**Comment by tuncer** [comment]
While thinking of workarounds, I wondered if one could write a source-only plugin (.erl) as part of the project, and if that would already be hook-ready (like in rebar2).

**Comment by ferd** [comment]
I've updated the hooks documentation to include the content mentioned in here.

@tuncer I don't believe we allow plugins to be defined from within the project there, since we'll attempt to fetch all plugins as if they were dependencies. The workaround there would be to define a plugin like `{plugins, [my_plugin]}.` and then put the source for the plugin inside `_checkouts/my_plugin/`. This could arguably work, but this is generally a mechanism used for the sake of local development and I don't think it would work if your app is fetched as a dependency later on. Maybe just for releases.

**Comment by tuncer** [comment]
It's not just for local development and was used in rebar2 for project-local plugins. Such plugins make no sense to share in a separate project and are part of rebar scripting.

If by saying it wouldn't work when fetched as a dependency you mean other projects won't have access to the project-local plugin, then that's correct and expected. If however you mean that the plugin won't be evaluated when the project is built because it's the dep of another one, then this is a bug.

**Comment by tsloughter** [comment]
Currently a plugin can not be in a dep. The rational for this was that this way the plugins (and deps of plugins) are not in the code path any other time than when they are run, so plugins and their deps can't interfere with other deps and transitive deps.

**Comment by tuncer** [comment]
Filed https://github.com/erlang/rebar3/issues/1273

**Comment by tuncer** [comment]
@matehat, can you give the rebar3-new-hooks branch a try, once the new port_compiler plugin has been published?

**Comment by tuncer** [comment]
@matehat, can you verify the rebar3-new-hooks branch with port_compiler 1.3.0 works for you as well?

**Comment by tuncer** [comment]
Fixed in master, requiring pc >=1.3.0.
